name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v -o apialerts .
      - name: Send Release Alert
        run: ./apialerts send -c developer -e ci.integration.release.cli -t "Release Build Passed" -m "CLI - Build for publish success" -g "CI/CD,CLI,Build" -l "https://github.com/apialerts/cli/actions"
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
